config/routes.rb
Rails.application.routes.draw do
  get '/mail_reset_password',   to: 'password#new'
  post '/mail_reset_password',   to: 'password#mail_reset'
  get '/reset_password',    to: 'password#reset'
  post '/reset_password',   to: 'password#reset_password'
  get 'teams/new'
  get 'teams/edit'
  get 'teams/delete'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :teams
  resources :projects
  resources :courses 
  resources :grades
end

app/models/grade.rb
class Grade < ApplicationRecord
    belongs_to :student, class_name: 'User'
    belongs_to :reviewer, class_name: 'User'
    belongs_to :team, class_name: "Team"

    validates :score, presence: true
    validates :remarks, presence: true, length: { maximum: 500 }



    def student_name
        @s=User.find_by(id: student_id) if @s.nil? 
        @s.name unless @s.nil?
    end

    def team_name
        @t=Team.find_by(id: team_id) if @t.nil?
        @t.name unless @t.nil?
    end
    def reviewer_name
        @s=User.find_by(id: reviewer_id) if@s.nil?
        @s.name unless @s.nil?       
    end

    def project_name
        @t=Team.find_by(id: team_id) if @t.nil?
        @p=Project.find_by(id: @t.project_id) if @p.nil?
        @p.project_name unless @p.nil?
    end
    def project_id
        @t=Team.find_by(id: team_id) if @t.nil?
        @t.project_id unless @t.nil?
    end    
    def course_no
        @t=Team.find_by(id: team_id) if @t.nil?
        @p=Project.find_by(id: @t.project_id) if @p.nil?
        @c=Course.find_by(id: @p.course_id) if @c.nil?        
        @c.course_no unless @c.nil?
    end
    def course_id
        @t=Team.find_by(id: team_id) if @t.nil?
        @p=Project.find_by(id: @t.project_id) if @p.nil?
        @p.course_id unless @p.nil?
    end
    def course
        @t=Team.find_by(id: team_id) if @t.nil?
        @p=Project.find_by(id: @t.project_id) if @p.nil?
        Course.find_by(id: @p.course_id)        
    end
    def grade_date
        updated_at.strftime("%m/%d/%Y")
    end
end

app/controllers/grades_controller.rb
=begin
  Grades controller processes the grade requests to view, create, modify, and delete grades.
	There are 5 different ways you can view the student grades.
	1. From the course details page - it lists all grades added for all students who enroll into the course
	2. From the project details page - it lists all grades added for all students who participate in the project
	3. From the team details page - it lists all grades addes for the students in the team.
	4. From the Grades menu
		For an instructor, it lists all grades that the instructor has graded
		For a TA, it lists all grades that the TA has graded
		For a student, it has 2 sub-menus
			A student can view all grades that have been added for him/her
			A student can view all grades he/she have added for his peer

  If the user navigates to view a grade details, the Grade Summary link will take the user back
  to the grade summary using the same grade viewing method. Ex. If the user were on the grade summary
  of a course, the Grade Summary link on the grade details page will navigate the user to the grade 
  summary of the same course.
=end

class GradesController < ApplicationController
  # only available to teachers, TAs, or students
  before_action :correct_team_grade_user, only: [:index, :show, :new, :edit, :update, :destroy]
  
  # set the @grade object 
  before_action :set_grade, only: %i[ show edit update destroy ]


  # GET /grades or /grades.json
  def index
    #check if the user wants to view the grades of a course
    course_id=request.query_parameters["course_id"]
    course_id=course_id.to_i unless course_id.nil?
    
    #check if the user wants to view the grades of a project
    project_id=request.query_parameters["project_id"]
    project_id=project_id.to_i unless project_id.nil?

    #check if the user wants to view the grades of a team    
    team_id=request.query_parameters["team_id"];
    team_id=team_id.to_i unless team_id.nil?

    #check if the student wants to view all his grades
    student_id=request.query_parameters["student_id"];
    student_id=student_id.to_i unless student_id.nil?

    #check if the student wants to view all grades he/she has added for his/her peers
    reviewer_id=request.query_parameters["reviewer_id"]
    reviewer_id=reviewer_id.to_i unless reviewer_id.nil?
    

    # if the user clicks on the Grade Summary link on the grade details page,
    # find the last grade summary filtering method and use it.
    if course_id.nil? and project_id.nil? and team_id.nil? and student_id.nil? and reviewer_id.nil?
      course_id = session[:course_id] if course_id.nil?
      project_id = session[:project_id] if project_id.nil?
      team_id = session[:team_id] if team_id.nil?
      student_id = session[:student_id] if student_id.nil?
      reviewer_id = session[:reviewer_id] if reviewer_id.nil?
    end

    # need to reset all in the session
    session[:course_id]=nil
    session[:project_id]=nil
    session[:team_id]=nil
    session[:student_id]=nil
    session[:reviewer_id]=nil

    if !student_id.nil?
      session[:student_id] = student_id
      @grade_title = 'My grades'
      @by_course = false
      @by_team = false
      @grades = Grade.all.reject { |g| g.student_id != student_id }
    elsif !reviewer_id.nil?
      @grade_title = "My peers' grades by me" unless current_user.admin?
      @grade_title = "All grades" if current_user.admin?
      @by_course = false
      @by_team = false
      session[:reviewer_id] = reviewer_id
      @grades = Grade.all.reject { |g| g.reviewer_id != current_user.id }
    elsif !team_id.nil?
      @grade_title = 'Grades of team'
      @by_course = false
      @by_project = false
      @by_team = true
      session[:team_id] = team_id
      @team = Team.find_by(id: team_id)
      @project = Project.find_by(id: @team.project_id)
      @course = Course.find_by(id: @project.course_id)
      @grades = Grade.all.reject { |g| g.team_id != team_id }
    elsif !project_id.nil?
      @grade_title = 'Grades of project'
      @by_course = false
      @by_project = true
      @by_team = false
      session[:project_id] = project_id
      @project = Project.find_by(id: project_id)
      @course = Course.find_by(id: @project.course_id)
      @grades = Grade.all.reject { |g| g.project_id != project_id }
    elsif !course_id.nil?
      @grade_title = 'Grades of class'
      @by_course = true
      @by_project = false
      @by_team = false
      session[:course_id] = course_id
      @course = Course.find_by(id: course_id)
      @grades = Grade.all.reject { |g| g.course_id != course_id }
    else
      @grade_title="All grades"
      @grades = Grade.all.reject{|g| g.reviewer_id != current_user.id}
    end
    
    @course=Course.new if @course.nil?
    
  end

  # GET /grades/1 or /grades/1.json
  def show; end

  # GET /grades/new
  def new
    @grade = Grade.new
    @grade.team_id = request.query_parameters['team_id']
    @grade.student_id = request.query_parameters['user_id']
  end

  # GET /grades/1/edit
  def edit; end

  # POST /grades or /grades.json
  def create
    @grade = Grade.new(grade_params)
    @grade.reviewer_id = current_user.id

    if @grade.save
      flash[:success] = 'Grade saved!'
      @team = Team.find(@grade.team_id)
      redirect_to @team
    else
      render 'new'
    end
  end

  # PATCH/PUT /grades/1 or /grades/1.json
  def update
    if @grade.update(grade_params)
      flash[:success] = 'The grade has been updated.'
      redirect_to @grade
    else
      render 'edit'
    end
  end

  # DELETE /grades/1 or /grades/1.json
  def destroy
    @grade.destroy
    flash[:success] = "The grade has been deleted"
    redirect_to grades_url  
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_grade
    @grade = Grade.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def grade_params
    params.require(:grade).permit(:remarks, :score, :student_id, :team_id)
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= form_with(model: @grade, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @grade %>  

  <%= f.label :"Score" %>
  <%= f.number_field  :score, class: 'form-control' %>
  <%= f.label :"Remarks" %>
  <%= f.text_area :remarks, class: 'form-control' %>
  <%= f.hidden_field :student_id %>
  <%= f.hidden_field :team_id %>


    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/grades/_grade.html.erb
<li>

  <p><%= link_to grade.student_name, grade %> </p>




  <p>
  <% if not @by_course and not @by_project and not @by_team %>
  <%= grade.course_no %> | <%= grade.project_name %> | <%= grade.team_name %>

  <% elsif not @by_project and not @by_team %>
  <%= grade.project_name %> | <%= grade.team_name %>

  <% elsif not @by_team %>
  <%= grade.team_name %>
  <% end %>
  </p>
  
  <p> 
  
  score: <%= link_to grade.score, grade_path(id: grade.id) %>
  <% if current_user.admin? or grade.reviewer_id==current_user.id %>
  <span class="separator">
  <%= link_to "delete this score", grade, method: :delete,  data: { confirm: "Are you sure?" } %>
  </span>
  <br>
  
  <% end %>
  <% if current_user.admin? %>
  graded by: <%= grade.reviewer_name %>
  <% end %>
  </p>
</li>

app/views/grades/edit.html.erb
<% provide(:title, "Grade a student") %>
<% provide(:button_text, 'Save grade') %>

<h1>Grade Student</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', project: @grade %>
  </div>
</div>

<br>
<%= link_to 'Back', @grade %> |
<%= link_to 'Grade Summary', grades_path %>

app/views/grades/index.html.erb
<% provide(:title, 'Grades') %>
<h3><%= @grade_title %></h3>
<hr>


<ul class="summary-list">
  
<% if @by_course %>
<p class="grade"><%= @course.course_no %></p>
<% end %>

<% if @by_project %>
<p><%= @course.course_no %> | <%= @project.project_name %></p>
<% end %>


<% if @by_team %>
<p><%= @course.course_no %> | <%= @project.project_name %> | <%= @team.name %></p>
<% end %>

<div class='grade-list'>
    <%= render @grades %>
</div>
</ul>

app/views/grades/new.html.erb
<% provide(:title, 'Grade Student') %>
<% provide(:button_text, 'Save grade') %>
<h1>New Grade</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/grades/show.html.erb
<% provide(:title, "Grade") %>

<h4><%= @grade.student_name %></h4>

<div class="score-details">
<p>
<%= @grade.course_no %> | <%= @grade.project_name %> | <%= @grade.team_name %>
</p>
<p>Score: <%= @grade.score %> (<%= @grade.grade_date %>)</p>
<% if current_user.admin?%>
graded by: <%= @grade.reviewer_name%>
<% end %>

<p class="remarks">
<%= @grade.remarks %> 
</p>
</div>
<hr>
<% if current_user.admin? or @grade.reviewer_id==current_user.id %>
<%= link_to 'Modify', edit_grade_path(@grade) %> |
<%= link_to "Delete", @grade, method: :delete,  data: { confirm: "Are you sure?" } %> |
<% end %>
<%= link_to 'Grade Summary', grades_path %>