config/routes.rb
Rails.application.routes.draw do
  get '/mail_reset_password',   to: 'password#new'
  post '/mail_reset_password',   to: 'password#mail_reset'
  get '/reset_password',    to: 'password#reset'
  post '/reset_password',   to: 'password#reset_password'
  get 'teams/new'
  get 'teams/edit'
  get 'teams/delete'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :teams
  resources :projects
  resources :courses 
  resources :grades
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  def new
  end

  def reset
    @user = User.find_by_email(params[:email])
  end

  def mail_reset
    @user = User.find_by_email(params[:email])
    if @user
      email_to_reset = params[:email]
      url = reset_password_url
      PasswordMailer.reset_password(email_to_reset, url).deliver_now
      flash[:success] = "Password reset email has sent to your email. Please check your inbox and spam"
      redirect_to login_url
    else 
      flash[:danger] = "Not a valid email, please try again!"
      redirect_to mail_reset_password_path
    end
  end

  def reset_password
    @user = User.find_by_email(params[:email])
    if @user
      password = params[:password]
      password_confirmation = params[:password_confirmation]
      if password != password_confirmation
        flash[:danger] = "Password and confirm password do not match"
        redirect_to request.fullpath + "?email=" + params[:email]
      elsif @user.update_attribute(:password, password)
        flash[:success] = "The password has been updated"
        redirect_to login_path
      end
    end
  end
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/views/password/new.html.erb
<% provide(:title, "Reset Password") %>
<h1>Reset Password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(url: mail_reset_password_path) do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.submit "Reset Password", class: "btn btn-primary" %>
  <% end %>
 </div>
</div>

app/views/password/reset.html.erb
<% provide(:title, "Reset Password") %>
<h1>Reset Password</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(url: reset_password_path, local: true) do |f| %>

      <%= hidden_field_tag :email, request.params[:email]%>

      <%= f.label :new_password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Reset Password", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>