config/routes.rb
Rails.application.routes.draw do
  get '/mail_reset_password',   to: 'password#new'
  post '/mail_reset_password',   to: 'password#mail_reset'
  get '/reset_password',    to: 'password#reset'
  post '/reset_password',   to: 'password#reset_password'
  get 'teams/new'
  get 'teams/edit'
  get 'teams/delete'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :teams
  resources :projects
  resources :courses 
  resources :grades
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :course
  validates :course_id, presence: true
  validates :project_name, presence: true, length: { maximum: 50 }
  has_many :teams, :dependent => :destroy


  def course_no
    @c=Course.find_by(id: course_id) if @c.nil?
    @c.course_no unless @c.nil?
  end
  def course
    @c=Course.find_by(id: course_id) if @c.nil?
  end
end

app/controllers/projects_controller.rb
=begin
  A control to process the project view, create, update, delete requests
  Only an instructor or TA can create, update, or delete a project
  The instructor or TA can only view the projects belong to courses that they teach.
=end
class ProjectsController < ApplicationController
  # only available to instructors and TAs
  before_action :correct_admin_user, only: [:index, :show, :new, :edit, :update, :destroy]

  # set @project object
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    # Only projects belong to the courses that the current user teaches
    @projects = Project.all.order("project_name asc").reject{|p| p.course.users.exclude? current_user}
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
   #load all courses that the current user teaches
   @my_courses=Course.all.order("course_no asc").reject{|c| c.users.exclude? current_user}

   if @my_courses.empty?
    flash[:danger]="Please create one or more courses before creating a project."
    redirect_to projects_path
  end

  end

  # GET /projects/1/edit
  def edit
    #load all courses that the current user teaches
    @my_courses=Course.all.order("course_no asc").reject{|c| c.users.exclude? current_user}

    if(@project.course.user_ids.exclude?(current_user.id))
      flash[:success]="You are not an instructor or TA of the course of this project"
      redirect_to @project
    else
        render 'edit'
    end
  end

  # POST /projects or /projects.json
  def create
    #byebug
    @project = Project.new(project_params)
    if @project.valid? &&@project.save(validate: false)
      flash[:success]="Project created!"
      redirect_to @project
    else
      render 'new'
    end
  end


  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    if @project.update(project_params)
      flash[:success]="The project has been updated."
      redirect_to @project
    else
      render 'edit'
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    # make sure the current user is an instructor or TA of the project before letting him/her
    # delete it
    if(@project.course.user_ids.exclude?(current_user.id))
      flash[:success]="You are not an instructor or TA of the course of this project"
      redirect_to @course
    else
      @project.destroy
      flash[:success] = "The project has been deleted"
      redirect_to projects_url  
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:project_name, :course_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: @project, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @project %>  
  <%= f.label :"Project name" %>
  <%= f.text_field :project_name, class: 'form-control' %>
  <%= f.label :Course %>
  <div class="select">
    <%= f.collection_select(:course_id, @my_courses, :id, :course_no) %>
  </div>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/projects/_project.html.erb
<li>
  <%= link_to project.project_name, project %> (<%= project.course_no %>)
  <% if current_user && current_user.admin? %>
    | <%= link_to "delete", project, method: :delete,  data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

app/views/projects/edit.html.erb
<% provide(:title, "Modify project") %>
<% provide(:button_text, 'Save changes') %>

<h1>Modify Project</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= render 'form', project: @project %>
  </div>
</div>


<hr>
<%= link_to 'Back', @project %> |
<%= link_to 'Project Summary', projects_path %>

app/views/projects/index.html.erb
<% provide(:title, 'All projects') %>
<h1>All projects</h1>
<hr>
<ul class="summary-list">
  <%= render @projects %>
</ul>
<% if current_user && current_user.admin? %>
  <div class="new-button">
    <%= link_to "Create a new project",  controller: "projects", action: "new"  %>
  </div>
<% end %>

app/views/projects/new.html.erb
<% provide(:title, 'Create a project') %>
<% provide(:button_text, 'Create project') %>
<h1>New Project</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>


<hr>
<%= link_to 'Project Summary', projects_path %>

app/views/projects/show.html.erb
<% provide(:title, @project.project_name) %>
Project: <%= @project.project_name %>
<div class="parent-info">
  Course: <%= @project.course_no %>
</div>
<br>
<div class='association-listing'>
  <span><%= pluralize(@project.teams.length, "teams") %> </span>
  <br>
  <% @project.teams.each do |t| %>
    <span class="section-item"><%= t.name %></span>
  <% end %>
</div>
<hr>
<%= link_to 'Modify Project', edit_project_path(@project) %> |
<%= link_to 'Project Summary', projects_path %>
<% if current_user && current_user.admin? %>
  | <%= link_to "Student Grades", grades_path(project_id: @project.id) %>
<% end %>