config/routes.rb
Rails.application.routes.draw do
  get '/mail_reset_password',   to: 'password#new'
  post '/mail_reset_password',   to: 'password#mail_reset'
  get '/reset_password',    to: 'password#reset'
  post '/reset_password',   to: 'password#reset_password'
  get 'teams/new'
  get 'teams/edit'
  get 'teams/delete'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :teams
  resources :projects
  resources :courses 
  resources :grades
end

app/views/layouts/_footer.html.erb
<footer class="footer">
 <small>
   The Bits Please Group - A peer review and rating application
</small>
<nav>
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
   </ul>
 </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Bits Please!", root_path, id: "logo" %>
    <nav>
    <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1"
            aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    </div>
  <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
      id="bs-example-navbar-collapse-1">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <% if staff_user %>
          <li><%= link_to "Courses", courses_path %></li>
          <li><%= link_to "Projects", projects_path %></li>
          <% end %>

          <% if staff_user or student_user %>
          <li><%= link_to "Teams", teams_path %></li>
          <% end %>
          <% if staff_user %>
            <li><%= link_to "Grades", grades_path(reviewer_id: current_user.id) %></li>
            <% end %>

          <% if not student_user %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>       
          <% if student_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Grades <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Grades for me", grades_path(student_id: current_user.id) %></li>
              <li><%= link_to "Grades for my peers", grades_path(reviewer_id: current_user.id) %></li>
            </ul>
          </li>
          <% end %>

          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Update My Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all',
                                       'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title><%= full_title(yield(:title)) %></title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= render 'layouts/rails_default' %>
   <%= render 'layouts/shim' %>
 </head>
 <body>
 <%= render 'layouts/header' %>   
 <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>

   </div>
  </body>
</html>